# -*- coding: utf-8 -*-
"""streamlit-friendly construction management system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zp-La_ogpfV3Ye-TTW3v5IJPU-LVum7o
"""

pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

pip install catboost

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

st.title("AI Driven Smart Construction Management")

uploaded_file = st.file_uploader("Upload Dataset", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    st.write("Dataset Preview", df.head())

    # Cleaning
    df.fillna(df.mean(numeric_only=True), inplace=True)

    # Feature selection
    target = st.selectbox("Select Target Column", df.columns)
    features = st.multiselect("Select Feature Columns", df.columns.drop(target))

    if features:
        X = df[features]
        y = df[target]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )

        # -------------------------------
        # Model Selection
        # -------------------------------
        model_name = st.selectbox(
            "Choose Model",
            [
                "Linear Regression",
                "Random Forest",
                "Decision Tree",
                "XGBoost",
                "LightGBM",
                "CatBoost"
            ]
        )

        if model_name == "Linear Regression":
            model = LinearRegression()

        elif model_name == "Random Forest":
            model = RandomForestRegressor(n_estimators=200, max_depth=10)

        elif model_name == "Decision Tree":
            model = DecisionTreeRegressor(max_depth=10)

        elif model_name == "XGBoost":
            model = XGBRegressor(
                n_estimators=300,
                learning_rate=0.05,
                max_depth=6,
                random_state=42
            )

        elif model_name == "LightGBM":
            model = LGBMRegressor(
                n_estimators=300,
                learning_rate=0.05,
                max_depth=6
            )

        elif model_name == "CatBoost":
            model = CatBoostRegressor(
                iterations=300,
                learning_rate=0.05,
                depth=6,
                verbose=0
            )

        # Train
        model.fit(X_train, y_train)

        # Predict
        y_pred = model.predict(X_test)

        # Metrics
        st.subheader("Model Performance")
        st.write("R2 Score:", r2_score(y_test, y_pred))
        st.write("MAE:", mean_absolute_error(y_test, y_pred))

        # -------------------------------
        # Compare ALL Models (🔥 BEST FEATURE)
        # -------------------------------
        if st.checkbox("Compare All Models"):
            models = {
                "Linear": LinearRegression(),
                "RF": RandomForestRegressor(),
                "DT": DecisionTreeRegressor(),
                "XGB": XGBRegressor(),
                "LGBM": LGBMRegressor(),
                "CatBoost": CatBoostRegressor(verbose=0)
            }

            results = {}

            for name, m in models.items():
                m.fit(X_train, y_train)
                pred = m.predict(X_test)
                results[name] = r2_score(y_test, pred)

            st.write("Model Comparison (R2 Score)")
            st.bar_chart(results)

        # -------------------------------
        # Custom Prediction
        # -------------------------------
        st.subheader("Make Prediction")

        input_data = []
        for col in features:
            val = st.number_input(f"{col}", value=0.0)
            input_data.append(val)

        if st.button("Predict"):
            pred = model.predict([input_data])
            st.success(f"Prediction: {pred[0]}")